---
description: Front End Web Developer
rssURL:
  main: https://ryandejaegher.com/feed/index.xml
rssLimit: "7"
mainSections:
- articles
enableGoogleTagManager: true
author: Ryan Dejaegher
tagline: Web Developer Â· Web Designer
debugGrid: false
siteDebug: 'true'
themeText: pink
algolia:
  vars: 
    - title
    - summary
    - date
    - publishdate
    - expirydate
    - permalink
  params:
    - categories
    - tags
    - excerpt

